name: Deploy Council Of Beer Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Set up .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'
  
        - name: Restore dependencies
          run: dotnet restore /home/runner/work/Council-Of-Beer/Council-Of-Beer/Back-end/Beer-Back-end/Beer-Back-end.sln
  
        - name: Build solution
          run: dotnet build /home/runner/work/Council-Of-Beer/Council-Of-Beer/Back-end/Beer-Back-end/Beer-Back-end.sln --configuration Release --no-restore
  
        - name: Publish API
          run: dotnet publish /home/runner/work/Council-Of-Beer/Council-Of-Beer/Back-end/Beer-Back-end/BeerAPI/BeerAPI.csproj --configuration Release --no-build --output ./publish
  
        - name: Upload publish artifact
          uses: actions/upload-artifact@v4
          with:
            name: beerapi-publish
            path: ./publish
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p "${{ secrets.SERVER_PORT }}" -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EduCloud VM
        run: |
          ssh -p "${{ secrets.SERVER_PORT }}" "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" << 'EOF'
            set -e

            cd /home/ubuntu/Council-Of-Beer

            git fetch origin
            git checkout main
            git pull origin main

            cd /home/ubuntu/Council-Of-Beer/Back-end/Beer-Back-end
            dotnet publish BeerAPI/BeerAPI.csproj -c Release

            sudo systemctl restart backend
            sudo systemctl status backend --no-pager
          EOF
